/* eslint-disable */
// Generated by Wrangler; string vars widened so ProcessEnv assignments typecheck.
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
		durableNamespaces: "DOQueueHandler";
	}
	interface Env {
		NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
		NEXT_TAG_CACHE_D1: D1Database;
		DB: D1Database;
		ASSETS: Fetcher;
		NODE_ENV: string;
		NEXT_PUBLIC_BASE_URL: string;
		NEXT_PUBLIC_SITE_URL: string;
		BREVO_FROM_EMAIL: string;
		BKASH_CHECKOUT_URL_BASE: string;
		AUTH_SECRET: string;
		CLOUDINARY_URL: string;
		BREVO_API_KEY: string;
		SUPER_ADMIN_EMAILS: string;
		BKASH_CHECKOUT_URL_APP_KEY: string;
		BKASH_CHECKOUT_URL_APP_SECRET: string;
		BKASH_CHECKOUT_URL_USER_NAME: string;
		BKASH_CHECKOUT_URL_PASSWORD: string;
		NEXT_CACHE_DO_QUEUE: DurableObjectNamespace<import("./.open-next/worker").DOQueueHandler>;
		WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "NEXT_PUBLIC_BASE_URL" | "NEXT_PUBLIC_SITE_URL" | "BREVO_FROM_EMAIL" | "BKASH_CHECKOUT_URL_BASE" | "AUTH_SECRET" | "CLOUDINARY_URL" | "BREVO_API_KEY" | "SUPER_ADMIN_EMAILS" | "BKASH_CHECKOUT_URL_APP_KEY" | "BKASH_CHECKOUT_URL_APP_SECRET" | "BKASH_CHECKOUT_URL_USER_NAME" | "BKASH_CHECKOUT_URL_PASSWORD">> {}
}
