/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts --include-runtime=false` (hash: baa77c39b28a66030a382d4f53d13f64)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env {
		ASSETS: Fetcher;
		SUPER_ADMIN_EMAILS: string;
		NEXT_PUBLIC_BASE_URL: string;
		NODE_ENV: string;
		VERCEL_URL: string;
		NEXT_PUBLIC_FIREBASE_API_KEY: string;
		NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
		NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
		NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
		NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
		NEXT_PUBLIC_FIREBASE_APP_ID: string;
		NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: string;
		FIREBASE_ADMIN_PROJECT_ID: string;
		FIREBASE_ADMIN_CLIENT_EMAIL: string;
		FIREBASE_ADMIN_PRIVATE_KEY: string;
		CLOUDINARY_URL: string;
		BREVO_API_KEY: string;
		BREVO_FROM_EMAIL: string;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPER_ADMIN_EMAILS" | "NEXT_PUBLIC_BASE_URL" | "NODE_ENV" | "VERCEL_URL" | "NEXT_PUBLIC_FIREBASE_API_KEY" | "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN" | "NEXT_PUBLIC_FIREBASE_PROJECT_ID" | "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET" | "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID" | "NEXT_PUBLIC_FIREBASE_APP_ID" | "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID" | "FIREBASE_ADMIN_PROJECT_ID" | "FIREBASE_ADMIN_CLIENT_EMAIL" | "FIREBASE_ADMIN_PRIVATE_KEY" | "CLOUDINARY_URL" | "BREVO_API_KEY" | "BREVO_FROM_EMAIL">> {}
}
